# Generated by Django 5.0.6 on 2024-05-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_vehicle', models.CharField(max_length=100)),
                ('top_speed', models.IntegerField()),
                ('fuel_efficiency', models.FloatField()),
                ('fuel_tank_capacity', models.IntegerField()),
                ('max_range', models.IntegerField()),
            ],
        ),
    ]
